# Generated by Django 4.2.4 on 2023-08-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_student_file_remove_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='car_name',
            field=models.CharField(default='Default Value', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='speed',
            field=models.IntegerField(default=50),
        ),
    ]
