# Generated by Django 4.2.4 on 2023-08-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_product_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
