# Generated by Django 4.2.4 on 2023-09-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_subject_subjectmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_name']},
        ),
    ]
